--------------------------------------------------------
--  File created - terça-feira-março-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  Auto Increment for Table UTENTE
--------------------------------------------------------
CREATE SEQUENCE utente_seq START WITH 1;
--------------------------------------------------------
--  DDL for Table UTENTE
--------------------------------------------------------

  CREATE TABLE "LEI"."UTENTE" 
    (
    "LOCAL_SEQ_NUMBER" NUMBER(10) DEFAULT utente_seq.nextval,
    "N_UTENTE" NUMBER(10,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"SEXO" VARCHAR2(2 BYTE), 
	"DATA_NASCIMENTO" DATE,
    "CC_ID" VARCHAR2(20 BYTE),
    "SNS" VARCHAR2(20 BYTE),
    "MORADA" VARCHAR2(50 BYTE),
    "CODIGO_POSTAL" VARCHAR2(20 BYTE),
    "LOCALIDADE" VARCHAR2(30 BYTE),
    "TELEMOVEL" VARCHAR2(10 BYTE),
    "EMAIL" VARCHAR2(30 BYTE),
    "OBS" VARCHAR2(150 BYTE),
    "DATA_INSERCAO" DATE DEFAULT CURRENT_DATE,
    "DATA_ATUALIZACAO" DATE DEFAULT CURRENT_DATE,
    "ESTADO" NUMBER(1) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "LEI_TABLES" ;
REM INSERTING into LEI.UTENTE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index UTENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEI"."UTENTE_PK" ON "LEI"."UTENTE" ("N_UTENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "LEI_TABLES" ;
--------------------------------------------------------
--  Constraints for Table UTENTE
--------------------------------------------------------

  ALTER TABLE "LEI"."UTENTE" MODIFY ("N_UTENTE" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("DATA_NASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("CC_ID" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("SNS" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("MORADA" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("CODIGO_POSTAL" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("LOCALIDADE" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("TELEMOVEL" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("DATA_INSERCAO" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("DATA_ATUALIZACAO" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "LEI"."UTENTE" ADD CONSTRAINT "UTENTE_PK" PRIMARY KEY ("N_UTENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "LEI_TABLES"  ENABLE;
